# kubectl apply -f date.yaml
# build.build.knative.dev/date created

# kubectl get build
# NAME   CREATED AT
# date   18s

# kubectl get pods
# NAME         READY   STATUS      RESTARTS   AGE
# date-sqxcm   0/1     Completed   0          25s

# kubectl logs date-sqxcm
# Build successful

apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
    name: date
spec:
    steps:
    - name: date
      image: debian:stable-slim
      args: ['/bin/date']
