apiVersion: serving.knative.dev/v1alpha1 # current version of Knative
kind: Service
metadata:
    name: helloworld-go # name of the app
    namespace: default # namespace of the app
spec:
    runLatest:
        configuration:
            revisionTemplate:
                spec:
                    container:
                        image: gcr.io/knative-samples/helloworld-go # URL to the image of the app
                        env:
                        - name: TARGET # enviornment variable printed out by the sample app
                        value: "Hello Universe!"
