apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
    name: app-from-source
    namespace: default
spec:
    runLatest:
        configuration:
            build:
                apiVersion: build.knative.dev/v1alpha1
                kind: Build
                spec:
                    serviceAccountName: nodejs-build-bot
                    source:
                        git:
                            url: https://github.com/pritidesai/experiments-with-knative.git
                            revision: app
                    template:
                        name: kaniko
                        arguments:
                            - name: IMAGE
                              value: docker.io/pritidesai/app-from-source:latest
                            - name: DOCKERFILE
                              value: ./sample-app/Dockerfile
            revisionTemplate:
                spec:
                    container:
                        image: docker.io/pritidesai/app-from-source:latest
                        imagePullPolicy: Always
                        env:
                            - name: SIMPLE_MSG
                              value: "Hello from the sample app!"
